spring.application.name=E-Commerce Platform
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=password123

# Tell Spring to automatically create our tables based on our Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true