### Create a new product
POST http://https://geetharu-elite-electronics-backend.hf.space/api/products
Content-Type: application/json

{
  "sku": "LAP-MAC-M3",
  "name": "MacBook Pro",
  "price": 1200.00,
  "stockQuantity": 15,
  "category": "laptop"
}

### Get all products
GET http://https://geetharu-elite-electronics-backend.hf.space/api/products

### Get a specific product by ID
GET http://https://geetharu-elite-electronics-backend.hf.space/api/products/1

### Update a product's price
PUT http://https://geetharu-elite-electronics-backend.hf.space/api/products/1
Content-Type: application/json

{
  "sku": "LAP-MAC-M3",
  "name": "MacBook Pro",
  "price": 1300.00,
  "stockQuantity": 15,
  "category": "laptop"
}

### Delete a specific product
DELETE http://https://geetharu-elite-electronics-backend.hf.space/api/products/1

### Get products by category
GET http://https://geetharu-elite-electronics-backend.hf.space/api/products/category/laptop