spring.application.name=E-Commerce Platform
stripe.api.key=sk_test_51T9hDiJvfCukoFWsY5ajPmmdvWtJYYFQEbpnLjIvSwdkQ5v8docU9UQZzfPyTYXzbJzLTZEKhFe66lnKyOFIGYGx00Ab1xcHOX
stripe.webhook.secret=whsec_e00c2000425dd009db8b8150aff81a7223db7001c565e17fb64c52f85326f065

# --- DATABASE CONNECTION ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password123}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE SETTINGS ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- SECURITY / AUTH SETTINGS ---
spring.main.allow-bean-definition-overriding=true

# --- CORS SETTINGS (For Deployment) ---
cors.allowed.origins=https://elite-electronics-store.vercel.app
cors.allowed.origin=http://localhost:5173