# --- LOCAL DATABASE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# --- LOCAL CORS ---
cors.allowed.origin=http://localhost:5173