# --- LIVE NEON DATABASE (Pulls securely from Hugging Face Environment Variables) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- LIVE VERCEL CORS ---
cors.allowed.origin=https://elite-electronics-store.vercel.app