# ? MASTER SWITCH (Change 'dev' to 'prod' when deploying to Hugging Face)
spring.profiles.active=dev

spring.application.name=E-Commerce Platform

# --- STRIPE KEYS (Test Keys) ---
stripe.api.key=sk_test_51T9hDiJvfCukoFWsY5ajPmmdvWtJYYFQEbpnLjIvSwdkQ5v8docU9UQZzfPyTYXzbJzLTZEKhFe66lnKyOFIGYGx00Ab1xcHOX
stripe.webhook.secret=whsec_e00c2000425dd009db8b8150aff81a7223db7001c565e17fb64c52f85326f065

# --- JPA / HIBERNATE SETTINGS ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-bean-definition-overriding=true